import { Rocket, FileText, BarChart3, Award, Upload, CheckCircle, Users, CreditCard, MapPin, TrendingUp, Target, FolderOpen, Download } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface JourneyStep {
  id: number;
  title: string;
  description: string;
  page: string; // Which page this step relates to
  duration: string;
  icon: LucideIcon;
  color: string;
  action: string; // CTA button text
  route?: string; // Optional route to navigate to
  selector?: string; // Optional data-testid for highlighting
  coachGuidance: {
    intro: string;
    instruction: string;
    tip?: string;
    nextStep?: string;
  };
  completionCriteria?: {
    checkField?: string; // Field to check in user/venture data
    minValue?: number; // For scores
    required?: boolean;
  };
  scoreThreshold?: {
    // Show different messages based on score
    low?: { max: number; message: string };
    medium?: { min: number; max: number; message: string };
    high?: { min: number; message: string };
  };
}

export const COACH_JOURNEY_STEPS: JourneyStep[] = [
  {
    id: 0,
    title: "Welcome to Second Chance",
    description: "Start your validation journey",
    page: "landing",
    duration: "2 min",
    icon: Rocket,
    color: "bg-blue-500",
    action: "Start Validation",
    route: "/onboarding-flow",
    coachGuidance: {
      intro: "Welcome! Let's transform your startup idea into an investor-ready venture.",
      instruction: "Click 'Start Validation' to begin your onboarding journey.",
      tip: "This process takes about 15 minutes and will give you your first ProofScore.",
      nextStep: "You'll provide founder details, venture information, and upload your pitch deck.",
    },
  },
  {
    id: 1,
    title: "Complete Onboarding",
    description: "Share your founder and venture details",
    page: "onboarding",
    duration: "10 min",
    icon: FileText,
    color: "bg-purple-500",
    action: "Continue Onboarding",
    route: "/onboarding-flow",
    coachGuidance: {
      intro: "Let's get your startup profile set up.",
      instruction: "Complete all onboarding steps: Founder Info → Venture Details → Team → Pitch Deck Upload.",
      tip: "Provide detailed information to get a more accurate ProofScore.",
      nextStep: "After completion, you'll receive your AI-powered ProofScore analysis.",
    },
    completionCriteria: {
      checkField: "onboardingComplete",
      required: true,
    },
  },
  {
    id: 2,
    title: "Review Your ProofScore",
    description: "Understand your validation score and insights",
    page: "dashboard",
    duration: "5 min",
    icon: BarChart3,
    color: "bg-green-500",
    action: "View Dashboard",
    route: "/dashboard",
    selector: "[data-testid='proofscore-display']",
    coachGuidance: {
      intro: "Your ProofScore reveals your startup's investment readiness.",
      instruction: "Review your score, dimension breakdown, and unlocked ProofTags.",
      tip: "ProofScores range from 0-100. Scores of 70+ unlock Deal Room access.",
      nextStep: "Explore the Validation Map to strengthen weak areas.",
    },
    scoreThreshold: {
      low: { max: 40, message: "Focus on building foundational proof through experiments." },
      medium: { min: 40, max: 70, message: "You're making progress! Complete validation experiments to boost your score." },
      high: { min: 70, message: "Excellent! You're ready for Deal Room access." },
    },
  },
  {
    id: 3,
    title: "Explore Validation Map",
    description: "Discover your personalized experiments",
    page: "validation-map",
    duration: "10 min",
    icon: MapPin,
    color: "bg-yellow-500",
    action: "Open Validation Map",
    route: "/validation-map",
    selector: "[data-testid='validation-map-grid']",
    coachGuidance: {
      intro: "Your Validation Map contains AI-curated experiments tailored to your startup.",
      instruction: "Review assigned experiments across Desirability, Feasibility, Viability, and Scaling spheres.",
      tip: "Each experiment tests a critical assumption about your business model.",
      nextStep: "Start running experiments and documenting results.",
    },
  },
  {
    id: 4,
    title: "Complete Your First Experiment",
    description: "Run and document a validation experiment",
    page: "validation-map",
    duration: "1-2 weeks",
    icon: Target,
    color: "bg-orange-500",
    action: "Start Experiment",
    route: "/validation-map",
    coachGuidance: {
      intro: "Time to validate your assumptions with real-world data!",
      instruction: "Pick an experiment, define your hypothesis, run it, and record your results.",
      tip: "Completed experiments unlock ProofTags and boost your credibility with investors.",
      nextStep: "Continue completing experiments to strengthen your validation.",
    },
    completionCriteria: {
      checkField: "hasCompletedExperiment",
      required: false,
    },
  },
  {
    id: 5,
    title: "Build Your ProofVault",
    description: "Upload validation documents and proof artifacts",
    page: "dashboard",
    duration: "15 min",
    icon: FolderOpen,
    color: "bg-indigo-500",
    action: "Upload to ProofVault",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "ProofVault is your organized repository of validation evidence.",
      instruction: "Upload documents like customer testimonials, metrics dashboards, demo videos, and financial models.",
      tip: "Each upload increases your VaultScore, showing investors you have systematic proof.",
      nextStep: "Aim for a VaultScore of 50+ by uploading diverse proof artifacts.",
    },
    completionCriteria: {
      checkField: "vaultScore",
      minValue: 30,
    },
  },
  {
    id: 6,
    title: "Download Your Certificate",
    description: "Get your ProofScore certificate",
    page: "dashboard",
    duration: "1 min",
    icon: Award,
    color: "bg-pink-500",
    action: "Download Certificate",
    route: "/dashboard",
    selector: "[data-testid='button-download-certificate']",
    coachGuidance: {
      intro: "Your ProofScore certificate validates your systematic approach.",
      instruction: "Download and share your certificate with accelerators, investors, or on LinkedIn.",
      tip: "This certificate demonstrates you've gone beyond a pitch deck to validate your venture.",
      nextStep: "Keep improving your score to increase your credibility.",
    },
  },
  {
    id: 7,
    title: "Unlock Deal Room Access",
    description: "Connect with verified investors",
    page: "dashboard",
    duration: "5 min",
    icon: Users,
    color: "bg-emerald-500",
    action: "Access Deal Room",
    route: "/dashboard",
    selector: "[data-testid='deal-room-section']",
    coachGuidance: {
      intro: "Deal Room connects high-scoring founders with active investors.",
      instruction: "If your ProofScore is 70+, you can unlock premium investor access.",
      tip: "Deal Room members get investor introductions, pitch practice, and fundraising support.",
      nextStep: "Complete payment to activate your Deal Room membership.",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 70,
    },
    scoreThreshold: {
      low: { max: 70, message: "Increase your ProofScore to 70+ to unlock Deal Room access." },
      high: { min: 70, message: "Congratulations! You qualify for Deal Room access." },
    },
  },
  {
    id: 8,
    title: "Activate Premium Features",
    description: "Unlock full platform access",
    page: "dashboard",
    duration: "3 min",
    icon: CreditCard,
    color: "bg-violet-500",
    action: "Upgrade Now",
    route: "/dashboard",
    coachGuidance: {
      intro: "Premium access unlocks investor matching, pitch coaching, and priority support.",
      instruction: "Complete payment to activate your Deal Room membership.",
      tip: "Investment: AED 499 or $149. Founders who use Deal Room are 3x more likely to secure meetings.",
      nextStep: "After payment, you'll get immediate access to our investor network.",
    },
    completionCriteria: {
      checkField: "hasDealRoomAccess",
      required: false,
    },
  },
  {
    id: 9,
    title: "Keep Building Proof",
    description: "Continuous validation journey",
    page: "dashboard",
    duration: "Ongoing",
    icon: TrendingUp,
    color: "bg-teal-500",
    action: "View Progress",
    route: "/dashboard",
    coachGuidance: {
      intro: "Validation is an ongoing process, not a one-time event.",
      instruction: "Keep running experiments, uploading proof, and improving your ProofScore.",
      tip: "Regular updates show investors you're making progress and learning from data.",
      nextStep: "Use the Validation Map and ProofVault to systematically strengthen your case.",
    },
  },
  // === COACH MODE JOURNEY STEPS (Post-Authentication) ===
  // These steps guide founders through their validation journey after completing onboarding
  
  // Step 10: Complete Dashboard Tutorial
  {
    id: 10,
    title: "Complete Dashboard Tutorial",
    description: "Learn how to navigate your validation hub",
    page: "dashboard",
    duration: "5 min",
    icon: Rocket,
    color: "bg-purple-700",
    action: "Start Tutorial",
    route: "/dashboard",
    selector: "[data-testid='dashboard-header']",
    coachGuidance: {
      intro: "Congratulations on completing onboarding! Let's explore your dashboard together.",
      instruction: "Follow the step-by-step tutorial to understand ProofScore, ProofVault, Deal Room, and all available features.",
      tip: "The tutorial only takes 5 minutes and will help you understand where everything is located.",
      nextStep: "After completing the tutorial, you'll be ready to start uploading proof documents and building your investor case.",
    },
    completionCriteria: {
      checkField: "dashboardTutorialCompleted",
      required: false,
    },
  },
  
  // Step 11: Make First Upload
  {
    id: 11,
    title: "Make Your First Upload",
    description: "Upload your first document to ProofVault",
    page: "dashboard",
    duration: "10 min",
    icon: Upload,
    color: "bg-blue-600",
    action: "Upload Files",
    route: "/dashboard",
    selector: "[data-testid='button-upload-files']",
    coachGuidance: {
      intro: "Great job completing the tutorial! Now let's build your ProofVault with real evidence.",
      instruction: "Click the 'Upload Files' button in the Validation Overview section. Select a folder (e.g., Product Proof), choose document type (e.g., Demo Video), add a description, and upload your file.",
      tip: "Start with your strongest proof - customer testimonials, product demos, or traction metrics make great first uploads!",
      nextStep: "After your first upload, you'll see your VaultScore increase and ProofCoach will celebrate with you!",
    },
    completionCriteria: {
      checkField: "vaultUploadCount",
      minValue: 1,
      required: false,
    },
  },
  
  // Step 13: Upload 10 Files
  {
    id: 13,
    title: "Upload 10 Files",
    description: "Build a foundational data room",
    page: "dashboard",
    duration: "1-2 hours",
    icon: FolderOpen,
    color: "bg-indigo-600",
    action: "Upload More",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "You're building momentum! Let's get to 10 uploaded files to create a solid foundation.",
      instruction: "Upload diverse proof types across different folders: Product Proof (demos, screenshots), Customer Proof (testimonials, case studies), Team Proof (bios, credentials), Financial Proof (models, metrics).",
      tip: "Founders with 10+ diverse documents are 50% more likely to match with investors. Quality and variety matter!",
      nextStep: "Once you hit 10 files, you'll unlock the next milestone: starting validation experiments.",
    },
    completionCriteria: {
      checkField: "vaultUploadCount",
      minValue: 10,
      required: false,
    },
  },
  
  // Step 14: Complete First Experiment
  {
    id: 14,
    title: "Complete Your First Validation Experiment",
    description: "Start testing your assumptions systematically",
    page: "validation-map",
    duration: "1-2 weeks",
    icon: Target,
    color: "bg-orange-600",
    action: "Start Experiment",
    route: "/validation-map",
    selector: "[data-testid='experiment-table-card']",
    coachGuidance: {
      intro: "Time to start validating! Click 'Validation Map' in the navbar to see your AI-curated experiments.",
      instruction: "Pick one high-impact experiment that tests your riskiest assumption. Click on it to add details: hypothesis, method, timeline, results. Mark it 'Completed' when done.",
      tip: "Failed experiments are just as valuable as successful ones - they show investors you're data-driven and learning!",
      nextStep: "Complete your first experiment to unlock a ProofTag and boost your credibility.",
    },
    completionCriteria: {
      checkField: "completedExperimentsCount",
      minValue: 1,
      required: false,
    },
  },
  
  // Step 15: Complete 3 Experiments
  {
    id: 15,
    title: "Complete 3 Validation Experiments",
    description: "Demonstrate systematic validation rigor",
    page: "validation-map",
    duration: "3-4 weeks",
    icon: CheckCircle,
    color: "bg-purple-600",
    action: "Complete Experiments",
    route: "/validation-map",
    selector: "[data-testid='experiment-table-card']",
    coachGuidance: {
      intro: "Great work on your first experiment! Now let's show systematic validation by completing 2 more.",
      instruction: "Pick 2 more high-impact experiments from your Validation Map. Run them across different spheres (Desirability, Feasibility, Viability, Scaling) to show balanced validation.",
      tip: "Each completed experiment unlocks ProofTags and increases your ProofScore. Balanced validation across spheres creates the strongest investor case!",
      nextStep: "After 3 completed experiments, export your Validation Map CSV as proof of systematic work.",
    },
    completionCriteria: {
      checkField: "completedExperimentsCount",
      minValue: 3,
      required: false,
    },
  },
  
  // Step 16: Export Validation Map CSV
  {
    id: 16,
    title: "Export Your Validation Map",
    description: "Download your validation timeline as proof",
    page: "validation-map",
    duration: "2 min",
    icon: Download,
    color: "bg-cyan-600",
    action: "Export CSV",
    route: "/validation-map",
    selector: "[data-testid='button-export-csv']",
    coachGuidance: {
      intro: "Excellent! You've completed 3 experiments. Now let's create exportable proof of your validation work.",
      instruction: "Click the 'Export CSV' button at the top of your Validation Map. This downloads all your experiment data, hypotheses, results, and decisions.",
      tip: "This CSV file is powerful evidence that you're rigorous and data-driven. Investors love seeing systematic validation!",
      nextStep: "Upload this CSV to your ProofVault under 'Problem Proof' folder to boost your VaultScore.",
    },
    completionCriteria: {
      checkField: "validationMapExported",
      required: false,
    },
  },
  
  // Step 17: Upload CSV to ProofVault
  {
    id: 17,
    title: "Upload Validation CSV to ProofVault",
    description: "Add validation timeline to your proof repository",
    page: "dashboard",
    duration: "3 min",
    icon: Upload,
    color: "bg-blue-700",
    action: "Upload CSV",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "Perfect! Now let's add your Validation Map CSV to ProofVault for investors to see.",
      instruction: "Navigate to ProofVault, click 'Upload Files', select folder: 'Problem Proof', document type: 'Validation Timeline', add description, and upload your CSV file.",
      tip: "Uploading systematic artifacts like validation timelines significantly boosts your VaultScore and investor credibility!",
      nextStep: "Continue uploading diverse proof documents to reach 20 total files.",
    },
    completionCriteria: {
      checkField: "validationMapUploadedToVault",
      required: false,
    },
  },
  
  // Step 18: Upload 20 Files
  {
    id: 18,
    title: "Upload 20 Total Files",
    description: "Build a comprehensive data room",
    page: "dashboard",
    duration: "2-3 hours",
    icon: FolderOpen,
    color: "bg-indigo-700",
    action: "Upload More",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "You're making great progress! Let's build a comprehensive data room with 20 total files.",
      instruction: "Upload diverse proof: customer testimonials, financial models, product demos, traction metrics, market research, competitive analysis, team credentials.",
      tip: "Investors want to see evidence from multiple angles. Aim for balance across Product, Customer, Team, and Financial proof types!",
      nextStep: "With 20 files uploaded, you're building serious credibility. Next milestone: Reach ProofScore 65+.",
    },
    completionCriteria: {
      checkField: "vaultUploadCount",
      minValue: 20,
      required: false,
    },
  },
  
  // Step 19: Reach ProofScore 65+
  {
    id: 19,
    title: "Reach ProofScore 65+",
    description: "You're 80% match with investors!",
    page: "dashboard",
    duration: "4-6 weeks",
    icon: TrendingUp,
    color: "bg-yellow-600",
    action: "Track Progress",
    route: "/dashboard",
    selector: "[data-testid='proofscore-display']",
    coachGuidance: {
      intro: "You're getting closer to Deal Room access! ProofScore 65+ means you're 80% match with investors.",
      instruction: "Focus on: (1) Complete more validation experiments, (2) Upload diverse proof documents, (3) Improve weak dimensions in your score breakdown.",
      tip: "Check your dimension breakdown to see which areas need work. Balanced scores across all dimensions create the strongest case!",
      nextStep: "Push to ProofScore 70+ to unlock Deal Room access and investor matching!",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 65,
      required: false,
    },
    scoreThreshold: {
      low: { max: 65, message: "Founders with a complete ProofVault are 50% more likely to match with investors." },
      high: { min: 65, message: "You're 80% match with investors in our Deal Room. Upload into your ProofVault to get access and connect." },
    },
  },
  
  // Step 20: Upload 30 Files
  {
    id: 20,
    title: "Upload 30 Total Files",
    description: "Build a comprehensive proof vault",
    page: "dashboard",
    duration: "3-4 hours",
    icon: FolderOpen,
    color: "bg-indigo-800",
    action: "Upload More",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "You're almost there! Let's build a truly comprehensive ProofVault with 30 total files.",
      instruction: "Continue uploading diverse proof artifacts across all categories. Include validation CSVs, customer case studies, product roadmaps, financial projections, and team credentials.",
      tip: "A comprehensive ProofVault with 30+ diverse documents shows investors you have systematic evidence, not just claims!",
      nextStep: "With 30 files, you're demonstrating serious commitment to validation. Next: Reach ProofScore 70+ to unlock Deal Room!",
    },
    completionCriteria: {
      checkField: "vaultUploadCount",
      minValue: 30,
      required: false,
    },
  },
  
  // Step 21: Reach ProofScore 70+ (Deal Room Unlocks!)
  {
    id: 21,
    title: "Reach ProofScore 70+",
    description: "Unlock Deal Room access!",
    page: "dashboard",
    duration: "6-8 weeks",
    icon: Target,
    color: "bg-green-700",
    action: "Track Progress",
    route: "/dashboard",
    selector: "[data-testid='proofscore-display']",
    coachGuidance: {
      intro: "This is the BIG milestone! ProofScore 70+ unlocks Deal Room access and investor matching!",
      instruction: "Focus on three key drivers: (1) Complete 3+ validation experiments, (2) Upload 30+ diverse proof documents to ProofVault, (3) Demonstrate real traction metrics.",
      tip: "ProofScore 70+ means you've got a high enough score to access the Deal Room. Investors typically look for 85+ for introductions, but 70 gets you in!",
      nextStep: "Once you reach 70+, the Deal Room section will activate and you can complete payment to unlock all features!",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 70,
      required: false,
    },
    scoreThreshold: {
      low: { max: 70, message: "You're 80% match with investors in our Deal Room. Upload into your ProofVault to get access and connect." },
      high: { min: 70, message: "You've got a high enough ProofScore to access the Deal Room. Investors typically look for a ProofScore of 85+ for an introduction." },
    },
  },
  
  // Step 22: Explore Deal Room Features
  {
    id: 22,
    title: "Explore Deal Room Features",
    description: "See what's available with your ProofScore 70+",
    page: "dashboard",
    duration: "5 min",
    icon: Users,
    color: "bg-emerald-600",
    action: "Explore Deal Room",
    route: "/dashboard",
    selector: "[data-testid='deal-room-section']",
    coachGuidance: {
      intro: "🎉 Congratulations! You've unlocked Deal Room access! Let's see what's available.",
      instruction: "Explore the Deal Room section on your dashboard. You'll see investor matching, community access, premium downloads, and pitch coaching features.",
      tip: "Deal Room gives you access to verified investors, premium downloads, community events, and personalized support. This is a major milestone!",
      nextStep: "Ready to unlock these features? Complete the payment to activate your Deal Room membership!",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 70,
      required: false,
    },
  },
  
  // Step 23: Complete Payment
  {
    id: 23,
    title: "Complete Payment",
    description: "Unlock Deal Room access and premium features",
    page: "dashboard",
    duration: "5 min",
    icon: CreditCard,
    color: "bg-yellow-700",
    action: "Make Payment",
    route: "/dashboard",
    selector: "[data-testid='deal-room-section']",
    coachGuidance: {
      intro: "You've qualified for Deal Room! Now let's unlock full access with a one-time payment.",
      instruction: "Click the payment button in the Deal Room section. Choose your preferred payment method (PayTabs or Telr) and complete the secure transaction.",
      tip: "One-time investment unlocks: (1) Investor matching and introductions, (2) Premium certificate and report downloads, (3) Community events and 1-on-1 sessions, (4) Pitch coaching and fundraising support. Founders with Deal Room access are 3x more likely to secure investor meetings!",
      nextStep: "After payment, all premium features will immediately unlock and you'll receive confirmation emails!",
    },
    completionCriteria: {
      checkField: "hasDealRoomAccess",
      required: false,
    },
  },
  
  // Step 24: Download Certificate
  {
    id: 24,
    title: "Download Your Certificate",
    description: "Get your official validation certificate",
    page: "dashboard",
    duration: "2 min",
    icon: Award,
    color: "bg-pink-600",
    action: "Download Certificate",
    route: "/dashboard",
    selector: "[data-testid='button-download-certificate']",
    coachGuidance: {
      intro: "Congratulations on completing your payment! Let's download your official ProofScore certificate.",
      instruction: "Navigate to the Document Downloads section and click 'Download Certificate'. This PDF validates your systematic approach to startup building.",
      tip: "Share your certificate on LinkedIn, in pitch decks, or with accelerators. It demonstrates you've gone beyond a pitch to validate your venture!",
      nextStep: "Next, download your detailed analysis report for deeper insights.",
    },
    completionCriteria: {
      checkField: "hasDealRoomAccess",
      required: false,
    },
  },
  
  // Step 25: Download Report
  {
    id: 25,
    title: "Download Your Detailed Report",
    description: "Get your comprehensive analysis document",
    page: "dashboard",
    duration: "2 min",
    icon: FileText,
    color: "bg-blue-700",
    action: "Download Report",
    route: "/dashboard",
    selector: "[data-testid='button-download-report']",
    coachGuidance: {
      intro: "Time to get your detailed analysis report with comprehensive insights!",
      instruction: "In the Document Downloads section, click 'Download Report'. This PDF contains your complete ProofScore breakdown, dimension analysis, and recommendations.",
      tip: "Use this report to identify exactly which areas to strengthen and how to improve your investor pitch!",
      nextStep: "Finally, access the investor community to start connecting!",
    },
    completionCriteria: {
      checkField: "hasDealRoomAccess",
      required: false,
    },
  },
  
  // Step 27: Complete 5 Experiments
  {
    id: 27,
    title: "Complete 5 Validation Experiments",
    description: "Show advanced validation rigor",
    page: "validation-map",
    duration: "6-8 weeks",
    icon: CheckCircle,
    color: "bg-purple-700",
    action: "Complete More",
    route: "/validation-map",
    selector: "[data-testid='experiment-table-card']",
    coachGuidance: {
      intro: "You're now in the excellence phase! Let's complete 5 total experiments to show advanced validation.",
      instruction: "Complete 2 more experiments, bringing your total to 5. Focus on experiments across different validation spheres for balanced proof.",
      tip: "5+ completed experiments unlock additional ProofTags and significantly boost your ProofScore toward 80+!",
      nextStep: "With 5 experiments, you're demonstrating systematic, rigorous validation that investors love to see.",
    },
    completionCriteria: {
      checkField: "completedExperimentsCount",
      minValue: 5,
      required: false,
    },
  },
  
  // Step 28: Reach ProofScore 80+
  {
    id: 28,
    title: "Reach ProofScore 80+",
    description: "Ready for investor introductions!",
    page: "dashboard",
    duration: "8-12 weeks",
    icon: TrendingUp,
    color: "bg-green-800",
    action: "Track Progress",
    route: "/dashboard",
    selector: "[data-testid='proofscore-display']",
    coachGuidance: {
      intro: "This is the investor introduction threshold! ProofScore 80+ means you're ready for direct investor connections.",
      instruction: "Continue completing experiments, uploading diverse proof, and demonstrating traction. Check your dimension breakdown to identify final improvements.",
      tip: "ProofScore 80+ tells investors you've done the work. You're not guessing - you have systematic evidence and are ready for serious conversations!",
      nextStep: "Reach 80+ to unlock investor introduction requests through our verified network!",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 80,
      required: false,
    },
    scoreThreshold: {
      low: { max: 80, message: "You've got a high enough ProofScore to access the Deal Room. Investors typically look for a ProofScore of 85+ for an introduction." },
      high: { min: 80, message: "You're ready for investor introductions — unlock the Deal Room and get connected to investors." },
    },
  },
  
  // Step 29: Upload 50 Files
  {
    id: 29,
    title: "Upload 50 Total Files",
    description: "Build an exceptional proof vault",
    page: "dashboard",
    duration: "5-6 hours",
    icon: FolderOpen,
    color: "bg-indigo-900",
    action: "Upload More",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "You're entering elite territory! Let's build an exceptional ProofVault with 50 total files.",
      instruction: "Upload comprehensive proof across all categories: product roadmaps, customer case studies, financial projections, team credentials, market research, competitive analysis, validation timelines, traction dashboards.",
      tip: "50+ diverse files shows investors you have exhaustive evidence. This level of preparation separates top founders from the rest!",
      nextStep: "With 50 files, you're demonstrating exceptional commitment to validation and investor readiness!",
    },
    completionCriteria: {
      checkField: "vaultUploadCount",
      minValue: 50,
      required: false,
    },
  },
  
  // Step 30: Become Investment Ready
  {
    id: 30,
    title: "You're Investment Ready!",
    description: "Complete your validation journey",
    page: "dashboard",
    duration: "Ongoing",
    icon: Award,
    color: "bg-gold-600",
    action: "Keep Building",
    route: "/dashboard",
    selector: "[data-testid='dashboard-header']",
    coachGuidance: {
      intro: "🎉 Congratulations! You've completed the entire ProofCoach journey and are truly investment-ready!",
      instruction: "You've achieved: ProofScore 80+, 50+ proof documents, 5+ completed experiments, Deal Room access, and community membership. This is exceptional!",
      tip: "Continue validating, uploading proof, and connecting with investors. Validation is ongoing - keep learning from data and improving your venture!",
      nextStep: "Use your ProofScore, certificate, and comprehensive ProofVault to confidently approach investors. You've done the work - now go raise that round!",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 80,
      required: false,
    },
  },
];

// Page-specific tutorial mechanics
export interface TutorialMechanic {
  id: string;
  page: string;
  title: string;
  description: string;
  selector: string; // data-testid to highlight
  tips?: string;
  location: string; // Where on screen to look
  order: number; // Sequence within page tutorial
}

export const TUTORIAL_MECHANICS: Record<string, TutorialMechanic[]> = {
  dashboard: [
    {
      id: "dashboard-welcome",
      page: "dashboard",
      title: "Welcome to Your Dashboard!",
      description: "Congratulations on completing your onboarding! You've successfully set up your founder profile, defined your venture, introduced your team, and received your ProofScore. This is your central hub for tracking validation progress and accessing all platform features.",
      selector: "[data-testid='dashboard-header']",
      location: "Top of page",
      order: 1,
    },
    {
      id: "dashboard-header",
      page: "dashboard",
      title: "Dashboard Overview",
      description: "Your dashboard is organized into sections: ProofScore display, Deal Room access, ProofVault management, document downloads, community access, leaderboard, and activity feed.",
      selector: "[data-testid='dashboard-header']",
      location: "Top of page",
      order: 2,
    },
    {
      id: "validation-overview",
      page: "dashboard",
      title: "Validation Overview",
      description: "Your current ProofScore (0-100) reflects your startup's investment readiness based on uploaded proof and completed experiments.",
      selector: "[data-testid='proofscore-display']",
      tips: "ProofScores of 70+ unlock Deal Room access.",
      location: "Upper section",
      order: 3,
    },
    {
      id: "deal-room",
      page: "dashboard",
      title: "Deal Room Access",
      description: "Unlock investor matching and fundraising support with a ProofScore of 70+. Book your first meeting here.",
      selector: "[data-testid='deal-room-section']",
      tips: "Deal Room members are 3x more likely to secure investor meetings.",
      location: "Upper right section",
      order: 4,
    },
    {
      id: "proof-vault",
      page: "dashboard",
      title: "ProofVault Management",
      description: "Upload and organize validation documents. Each upload increases your VaultScore and strengthens your investor case.",
      selector: "[data-testid='proof-vault-section']",
      tips: "Upload diverse artifacts: testimonials, metrics, videos, financial models.",
      location: "Main section",
      order: 5,
    },
    {
      id: "document-downloads",
      page: "dashboard",
      title: "Downloads Available",
      description: "Download your validation certificate and analysis report after unlocking Deal Room access.",
      selector: "[data-testid='document-downloads-section']",
      tips: "These documents are perfect for investor decks and pitch materials.",
      location: "Lower left section",
      order: 6,
    },
    {
      id: "community-access",
      page: "dashboard",
      title: "Community Access",
      description: "Connect with other founders and join exclusive events like Founders Live Egypt and UAE.",
      selector: "[data-testid='community-access-section']",
      tips: "Book 1-on-1 sessions via Calendly if you have Deal Room access.",
      location: "Lower right section",
      order: 7,
    },
    {
      id: "leaderboard",
      page: "dashboard",
      title: "Leaderboard",
      description: "See how you rank against other founders based on ProofScore and ProofTags unlocked.",
      selector: "[data-testid='leaderboard-section']",
      location: "Bottom left section",
      order: 8,
    },
    {
      id: "activity-feed",
      page: "dashboard",
      title: "Recent Activity",
      description: "Track your latest platform interactions, uploads, and achievements in real-time.",
      selector: "[data-testid='activity-feed-section']",
      location: "Bottom right section",
      order: 9,
    },
    {
      id: "navigate-to-validation-map",
      page: "dashboard",
      title: "Explore Your Validation Map",
      description: "Now that you've explored your dashboard, it's time to start validating your startup! Click 'Validation Map' in the top navigation bar to access your personalized experiments.",
      selector: "[data-testid='link-validation-map']",
      tips: "The Validation Map contains AI-curated experiments tailored to your startup. Completing experiments unlocks ProofTags and boosts your ProofScore from its current level to 70+ for Deal Room access.",
      location: "Top navigation bar",
      order: 10,
    },
  ],
  "validation-map": [
    {
      id: "what-are-experiments",
      page: "validation-map",
      title: "What are Validation Experiments?",
      description: "Experiments are systematic tests to validate your startup's assumptions. Each experiment helps you gather evidence about whether your business model works, reducing risk and increasing investor confidence.",
      selector: "[data-testid='validation-map-intro']",
      tips: "Completing experiments unlocks ProofTags and boosts your ProofScore, making you more investment-ready.",
      location: "Top section",
      order: 1,
    },
    {
      id: "validation-spheres",
      page: "validation-map",
      title: "Four Validation Spheres",
      description: "Your experiments span four critical areas: Desirability (do customers want it?), Feasibility (can we build it?), Viability (will it make money?), and Scaling (can we grow it?).",
      selector: "[data-testid='validation-map-intro']",
      tips: "Balanced validation across all four spheres creates a compelling investor case.",
      location: "Introduction card",
      order: 2,
    },
    {
      id: "add-experiment",
      page: "validation-map",
      title: "Adding Experiments",
      description: "Click 'Add Experiment' to choose from 44 AI-curated experiments designed for your startup stage, or create custom experiments that match your unique validation needs.",
      selector: "[data-testid='experiment-header-card']",
      tips: "Start with 3-5 high-impact experiments. Quality matters more than quantity.",
      location: "Top right buttons",
      order: 3,
    },
    {
      id: "experiment-filters",
      page: "validation-map",
      title: "Search & Filter Tools",
      description: "Use search to find specific experiments, filter by validation sphere (Desirability, Feasibility, Viability, Scaling), or filter by status (pending, in-progress, completed) to stay organized.",
      selector: "[data-testid='experiment-filters-card']",
      tips: "Focus on completing experiments in areas where you have the least evidence first.",
      location: "Filter section",
      order: 4,
    },
    {
      id: "table-structure",
      page: "validation-map",
      title: "Understanding Your Experiment Table",
      description: "Each column represents a step in the scientific method: your hypothesis, what you'll measure, actual results, analysis (why), insights learned, and your decision (pivot, persevere, or iterate). Each row has action buttons (Edit, Delete, Complete) and supports inline editing—just click any editable field and changes auto-save after 500ms.",
      selector: "[data-testid='experiment-table-card']",
      tips: "Mark experiments 'Complete' to unlock ProofTags. This structured approach helps you think like a scientist about your business.",
      location: "Table area",
      order: 5,
    },
    {
      id: "export-csv",
      page: "validation-map",
      title: "Export to CSV",
      description: "After completing at least 3 experiments, use the 'Export CSV' button to download your validation map. This CSV file can be uploaded to your ProofVault to boost your VaultScore and strengthen your investor materials.",
      selector: "[data-testid='experiment-header-card']",
      tips: "The CSV export captures all your experiment data in a format investors can easily review. It's a powerful artifact showing systematic validation.",
      location: "Top right section",
      order: 6,
    },
  ],
  "experiment-details": [
    {
      id: "experiment-overview",
      page: "experiment-details",
      title: "Experiment Overview",
      description: "View your experiment's title, current status (pending, in-progress, completed), validation sphere (Desirability, Viability, Feasibility, Scaling), and associated ProofTag (if completed). The definition explains what this experiment tests.",
      selector: "[data-testid='experiment-modal-header']",
      tips: "Completed experiments unlock ProofTags that boost your ProofScore and show investors systematic validation.",
      location: "Top section",
      order: 1,
    },
    {
      id: "core-assumption",
      page: "experiment-details",
      title: "Core Assumption",
      description: "This is the fundamental belief your experiment tests. It's pre-populated from the AI-curated experiment library and helps you focus on what you're validating.",
      selector: "[data-testid='experiment-core-assumption']",
      tips: "Every successful startup is built on validated assumptions, not guesses.",
      location: "First field",
      order: 2,
    },
    {
      id: "hypothesis-field",
      page: "experiment-details",
      title: "Your Hypothesis",
      description: "Write your specific, testable prediction. Click Edit to activate the rich text editor and document what you expect to happen. A good hypothesis is clear, measurable, and time-bound.",
      selector: "[data-testid='experiment-hypothesis']",
      tips: "Example: 'If we add social proof testimonials, we'll see 15% increase in sign-ups within 2 weeks.'",
      location: "Second field",
      order: 3,
    },
    {
      id: "target-metrics",
      page: "experiment-details",
      title: "Target Behaviour & Metric",
      description: "These fields define what customer action you're testing (behaviour) and how you'll measure success (metric). They guide you to think scientifically about validation.",
      selector: "[data-testid='experiment-target-behaviour']",
      tips: "Combine both: What should users do? How will you measure it?",
      location: "Middle fields",
      order: 4,
    },
    {
      id: "actual-results",
      page: "experiment-details",
      title: "Actual Results",
      description: "Record what actually happened. Use the rich text editor to add data, screenshots, metrics, quotes—any evidence from your experiment. This is your proof.",
      selector: "[data-testid='experiment-results']",
      tips: "Be honest. Negative results teach as much as positive ones. Investors value learning velocity.",
      location: "Results section",
      order: 5,
    },
    {
      id: "analysis-insights",
      page: "experiment-details",
      title: "Analysis & Insights",
      description: "'Why?' analyzes what caused the results. 'New Insights' captures unexpected learnings. Both help you build institutional knowledge about your market and customers.",
      selector: "[data-testid='experiment-why']",
      tips: "This is where pivots are born. Document surprises—they often reveal better opportunities.",
      location: "Analysis fields",
      order: 6,
    },
    {
      id: "decision-making",
      page: "experiment-details",
      title: "Decision",
      description: "Choose your path forward: Go (validated, scale it), Start (begin this initiative), Pivot (change direction), or Learn/Measure (need more data). This turns validation into action.",
      selector: "[data-testid='experiment-decision']",
      tips: "Making decisions based on data (not opinions) is what separates funded startups from failed ones.",
      location: "Bottom field",
      order: 7,
    },
    {
      id: "edit-mode",
      page: "experiment-details",
      title: "Edit & Save",
      description: "Click the Edit button (top right) to enable editing mode. Update any editable fields using the rich text editor for formatting. When done, click Save Changes to update your experiment.",
      selector: "[data-testid='button-edit-experiment']",
      tips: "Changes auto-save in the table view, but modal editing gives you full rich text formatting capabilities.",
      location: "Top right buttons",
      order: 8,
    },
  ],
  "onboarding-founder": [
    {
      id: "founder-intro",
      page: "onboarding-founder",
      title: "Welcome to Onboarding!",
      description: "Let's get started with your founder profile. This information helps us understand your background and expertise, which factors into your ProofScore calculation.",
      selector: "[data-testid='onboarding-founder-container']",
      tips: "The onboarding process takes about 10-15 minutes total. You can save progress and return later if needed.",
      location: "Full page",
      order: 1,
    },
    {
      id: "founder-name",
      page: "onboarding-founder",
      title: "Your Full Name",
      description: "Enter your full name as it appears professionally. This will be used on your ProofScore certificate and investor communications.",
      selector: "[data-testid='input-full-name']",
      tips: "Use your real name—authenticity builds trust with investors.",
      location: "First field",
      order: 2,
    },
    {
      id: "founder-email",
      page: "onboarding-founder",
      title: "Email Address",
      description: "Provide your primary email address. This will be used for login, notifications about your validation progress, and investor communications.",
      selector: "[data-testid='input-email']",
      tips: "Use a professional email you check regularly—important updates about your ProofScore and Deal Room will be sent here.",
      location: "Second field",
      order: 3,
    },
    {
      id: "founder-position",
      page: "onboarding-founder",
      title: "Position/Role",
      description: "Specify your role in the venture (e.g., CEO, CTO, Founder, Co-Founder). This helps us understand your leadership position and responsibilities.",
      selector: "[data-testid='input-position-role']",
      tips: "If you have multiple roles, list the primary one. Technical roles (CTO, Lead Engineer) can positively influence feasibility scores.",
      location: "Third field",
      order: 4,
    },
    {
      id: "founder-demographics",
      page: "onboarding-founder",
      title: "Age & Gender (Optional)",
      description: "Providing demographic information is optional but helps us understand founder diversity patterns. This data is kept private and used only for anonymized analytics.",
      selector: "[data-testid='input-age']",
      tips: "These fields are optional and won't affect your ProofScore. We use this data to improve our platform and support diverse founder communities.",
      location: "Age and Gender fields",
      order: 5,
    },
    {
      id: "founder-residence",
      page: "onboarding-founder",
      title: "Residence Location",
      description: "Enter your current city and country (e.g., 'Dubai, UAE' or 'San Francisco, USA'). This helps us connect you with local investor networks and relevant resources.",
      selector: "[data-testid='input-residence']",
      tips: "Your location influences which payment options and investor networks we can offer you.",
      location: "Residence field",
      order: 6,
    },
    {
      id: "founder-linkedin",
      page: "onboarding-founder",
      title: "LinkedIn Profile",
      description: "Add your LinkedIn profile URL. A complete LinkedIn profile with relevant experience, education, and network demonstrates credibility to investors.",
      selector: "[data-testid='input-linkedin']",
      tips: "Investors often research founders on LinkedIn before meetings. Make sure your profile is up-to-date and professional.",
      location: "LinkedIn field",
      order: 7,
    },
    {
      id: "founder-technical",
      page: "onboarding-founder",
      title: "Technical Background",
      description: "Toggle this on if you have technical skills like coding, engineering, data science, or product development. Tech-capable founders often score higher in feasibility validation.",
      selector: "[data-testid='switch-is-technical']",
      tips: "Technical founders can build MVPs faster and validate solutions more efficiently. But non-technical founders with great teams also succeed!",
      location: "Technical toggle",
      order: 8,
    },
    {
      id: "founder-submit",
      page: "onboarding-founder",
      title: "Continue to Venture Info",
      description: "Once you've completed your founder profile, click 'Next: Venture Info' to move on to describing your startup, problem, solution, and market opportunity.",
      selector: "[data-testid='button-continue-venture']",
      tips: "All this information can be edited later from your dashboard settings.",
      location: "Bottom button",
      order: 9,
    },
  ],
  "onboarding-venture": [
    {
      id: "venture-congratulations",
      page: "onboarding-venture",
      title: "🎉 Congratulations!",
      description: "Congratulations on completing your founder profile! You've successfully shared your background, expertise, and vision. Now let's move on to your venture details.",
      selector: "[data-testid='onboarding-venture-container']",
      location: "Full page",
      order: 1,
    },
    {
      id: "venture-intro",
      page: "onboarding-venture",
      title: "Tell Us About Your Startup",
      description: "Let's capture details about your venture. This information is critical for your ProofScore calculation and helps us assign relevant validation experiments tailored to your business.",
      selector: "[data-testid='onboarding-venture-container']",
      tips: "Be specific and honest—our AI analyzes your pitch deck against these details to generate accurate insights.",
      location: "Full page",
      order: 2,
    },
    {
      id: "venture-name",
      page: "onboarding-venture",
      title: "Startup Name",
      description: "Enter your company's official name. This will be used in your ProofScore certificate, investor communications, and all platform documentation.",
      selector: "[data-testid='input-company-name']",
      tips: "Use your registered business name or the name you plan to register. This appears on all official documents.",
      location: "First field",
      order: 3,
    },
    {
      id: "venture-industry",
      page: "onboarding-venture",
      title: "Industry Selection",
      description: "Select your primary industry sector. This helps us connect you with relevant investors, benchmarks, and market opportunities specific to your domain.",
      selector: "[data-testid='select-industry']",
      tips: "Choose the industry that best describes your core business. This affects which validation experiments we assign to you.",
      location: "Industry field",
      order: 4,
    },
    {
      id: "venture-geography",
      page: "onboarding-venture",
      title: "Target Geography",
      description: "Select your target geography or market region. This indicates where you'll operate or seek customers, helping us provide region-specific insights and investor connections.",
      selector: "[data-testid='select-geography']",
      tips: "Geography should reflect your primary market. You can always expand to other regions later as you grow.",
      location: "Geography field",
      order: 5,
    },
    {
      id: "venture-business-model",
      page: "onboarding-venture",
      title: "Business Model",
      description: "Define how your startup makes money. Your business model (B2B SaaS, Marketplace, E-commerce, etc.) influences which validation experiments we assign and how investors evaluate you.",
      selector: "[data-testid='select-business-model']",
      tips: "Choose the model that best describes your revenue generation approach. This affects your ProofScore calculation.",
      location: "Business Model field",
      order: 6,
    },
    {
      id: "venture-revenue-stage",
      page: "onboarding-venture",
      title: "Revenue Stage",
      description: "Indicate your current revenue stage: Pre-Revenue (no paying customers yet), Early Revenue (first customers), or Scaling (growing revenue). This helps us provide stage-appropriate guidance.",
      selector: "[data-testid='select-revenue-stage']",
      tips: "Be honest about your stage—early-stage startups get different experiments than scaling companies. Both paths can succeed!",
      location: "Revenue Stage field",
      order: 7,
    },
    {
      id: "venture-product-status",
      page: "onboarding-venture",
      title: "Product Status",
      description: "Indicate your product development stage: Mockup (design/wireframes), Prototype (working demo), or Launched (live product). This determines which validation pathways are most relevant for you.",
      selector: "[data-testid='select-product-status']",
      tips: "Your product status affects which ProofTags you can unlock and which experiments are assigned to you.",
      location: "Product Status field",
      order: 8,
    },
    {
      id: "venture-website",
      page: "onboarding-venture",
      title: "Website (Optional)",
      description: "Add your company website URL if you have one. A live website demonstrates traction and professionalism to investors, though it's not required at early stages.",
      selector: "[data-testid='input-website']",
      tips: "No website yet? No problem! Many successful startups begin without one. You can add it later as you grow.",
      location: "Website field",
      order: 9,
    },
    {
      id: "venture-description",
      page: "onboarding-venture",
      title: "Startup Description",
      description: "Write a clear, compelling description of what your startup does, the problem you solve, and your unique value proposition. This is analyzed by our AI for clarity and market fit.",
      selector: "[data-testid='textarea-problem-statement']",
      tips: "Great descriptions answer: What problem exists? Who has it? How do you solve it differently? Keep it concise and specific.",
      location: "Description field",
      order: 10,
    },
    {
      id: "venture-social",
      page: "onboarding-venture",
      title: "Social Media Links (Optional)",
      description: "Add links to your company's LinkedIn, Twitter/X, and Instagram profiles. Social media presence shows market engagement and can boost investor confidence.",
      selector: "[data-testid='input-linkedin-url']",
      tips: "Active social channels demonstrate community building and marketing efforts. Optional but recommended for visibility.",
      location: "Social media fields",
      order: 11,
    },
    {
      id: "venture-submit",
      page: "onboarding-venture",
      title: "Continue to Team",
      description: "Once you've completed all venture details, click 'Next: Team Members' to add your team (optional) or proceed directly to uploading your pitch deck.",
      selector: "[data-testid='button-continue-team']",
      tips: "Strong teams increase ProofScore significantly—investors bet on people as much as ideas!",
      location: "Bottom button",
      order: 12,
    },
  ],
  "onboarding-team": [
    {
      id: "team-congratulations",
      page: "onboarding-team",
      title: "🎉 Great Work!",
      description: "Great work on your venture details! You've successfully defined your startup, market, and business model. Now let's introduce your team.",
      selector: "[data-testid='onboarding-team-container']",
      location: "Full page",
      order: 1,
    },
    {
      id: "team-intro",
      page: "onboarding-team",
      title: "Build Your Team Profile",
      description: "Let's introduce your team. Add up to 4 team members—investors love seeing complementary skills and diverse expertise. If you're solo for now, you can skip this step.",
      selector: "[data-testid='onboarding-team-container']",
      tips: "Teams with balanced skills (tech + business, for example) tend to score higher.",
      location: "Full page",
      order: 2,
    },
    {
      id: "team-add-button",
      page: "onboarding-team",
      title: "Add Team Member Button",
      description: "Click the 'Add Team Member' button to open the form and add a team member. You can add up to 4 team members to showcase your team's strength and diverse expertise.",
      selector: "[data-testid='button-add-team-member']",
      tips: "Maximum 4 team members can be added. Include co-founders, key hires, and advisors who actively contribute to your startup.",
      location: "Add button",
      order: 3,
    },
    {
      id: "team-click-instruction",
      page: "onboarding-team",
      title: "Click to Open Form",
      description: "Click the highlighted button to reveal the team member form. You'll then fill in details about each team member including their name, role, experience, and contact information.",
      selector: "[data-testid='button-add-team-member']",
      tips: "The form will appear below the button once you click it.",
      location: "Add button",
      order: 4,
    },
    {
      id: "team-name-role",
      page: "onboarding-team",
      title: "Team Member Name & Role",
      description: "Enter the team member's full name and their role in your startup (e.g., CTO, CMO, Co-Founder, Lead Engineer). These fields are required and help investors understand your team structure.",
      selector: "[data-testid='input-team-fullname']",
      tips: "Use professional names and specific role titles. Technical roles demonstrate execution capability to investors.",
      location: "Name and Role fields",
      order: 5,
    },
    {
      id: "team-email-linkedin",
      page: "onboarding-team",
      title: "Email & LinkedIn Profile",
      description: "Provide the team member's email address (required) and LinkedIn profile URL (optional but recommended). LinkedIn profiles help investors verify your team's experience and credentials.",
      selector: "[data-testid='input-team-email']",
      tips: "Complete LinkedIn profiles with relevant experience, education, and connections build credibility.",
      location: "Email and LinkedIn fields",
      order: 6,
    },
    {
      id: "team-experience",
      page: "onboarding-team",
      title: "Team Member Experience",
      description: "Describe the team member's relevant experience, skills, and background. Include years of experience, previous companies, notable achievements, or domain expertise that strengthens your startup.",
      selector: "[data-testid='input-team-experience']",
      tips: "Highlight achievements like 'Former Google engineer', '15+ years in fintech', or 'Built and sold 2 startups'.",
      location: "Experience field",
      order: 7,
    },
    {
      id: "team-social-media",
      page: "onboarding-team",
      title: "Social Media Profiles (Optional)",
      description: "Add the team member's Twitter, Instagram, or GitHub profile URLs. Social presence demonstrates industry engagement and thought leadership, especially valuable for technical team members.",
      selector: "[data-testid='input-team-twitter']",
      tips: "GitHub profiles are particularly impressive for technical roles. Active Twitter/X presence shows industry thought leadership.",
      location: "Social media fields",
      order: 8,
    },
    {
      id: "team-demographics",
      page: "onboarding-team",
      title: "Age & Gender (Optional)",
      description: "Optionally provide the team member's age and gender. This demographic information helps us track diversity metrics and connect you with inclusive investor networks.",
      selector: "[data-testid='input-team-age']",
      tips: "This information is optional and confidential. We use it only for diversity analytics and to improve our platform for all founders.",
      location: "Age and Gender fields",
      order: 9,
    },
    {
      id: "team-background",
      page: "onboarding-team",
      title: "Additional Background",
      description: "Add any additional background information that strengthens this team member's profile—education, certifications, awards, publications, or unique domain expertise.",
      selector: "[data-testid='input-team-background']",
      tips: "Examples: 'MBA from Stanford', 'Published researcher in AI', 'Certified AWS Solutions Architect', or 'Former Olympic athlete'.",
      location: "Background field",
      order: 10,
    },
    {
      id: "team-cofounder-status",
      page: "onboarding-team",
      title: "Co-Founder Status",
      description: "Check this box if this person is a co-founder (equity holder with founding role). Co-founders demonstrate long-term commitment and skin in the game, which investors value highly.",
      selector: "[data-testid='checkbox-team-is-cofounder']",
      tips: "Co-founders vs. employees: Co-founders typically have equity and were there from the start. Early employees can become co-founders if given equity.",
      location: "Co-founder checkbox",
      order: 11,
    },
    {
      id: "team-submit-member",
      page: "onboarding-team",
      title: "Add Team Member",
      description: "Once you've filled in the team member details, click 'Add Member' to save them to your team. You can add up to 4 members total.",
      selector: "[data-testid='button-submit-team-member']",
      tips: "After adding a member, you can add more by clicking 'Add Team Member' again, or proceed to the next step.",
      location: "Submit button",
      order: 12,
    },
    {
      id: "team-continue",
      page: "onboarding-team",
      title: "Continue to Upload",
      description: "When you're done adding team members, click 'Next: Upload Pitch Deck' to proceed. If you're a solo founder, you can skip adding team members and click this button directly—you can always add team members later as you grow.",
      selector: "[data-testid='button-continue-upload']",
      tips: "Solo founders can succeed too—focus on showing traction and learning velocity. Strong teams increase ProofScore, but it's not required.",
      location: "Bottom button",
      order: 13,
    },
  ],
  "onboarding-upload": [
    {
      id: "upload-congratulations",
      page: "onboarding-upload",
      title: "🎉 Excellent!",
      description: "Excellent! Your profile is taking shape. You've completed your founder profile, venture details, and team introduction. Now for the most important step—let's get your pitch deck!",
      selector: "[data-testid='upload-zone']",
      location: "Full page",
      order: 1,
    },
    {
      id: "upload-intro",
      page: "onboarding-upload",
      title: "Upload Your Pitch Deck",
      description: "Upload your pitch deck and our AI will analyze it to generate your ProofScore and assign personalized validation experiments.",
      selector: "[data-testid='upload-zone']",
      tips: "Accepted formats: PDF, PPTX, PPT. Max size: 10MB. Make sure your deck has slides about problem, solution, market, traction, and team.",
      location: "Upload area",
      order: 2,
    },
    {
      id: "upload-requirements",
      page: "onboarding-upload",
      title: "What Makes a Good Deck?",
      description: "Include slides covering: problem statement, solution/product, market opportunity, business model, traction metrics, competitive landscape, and team. The more complete your deck, the better your ProofScore.",
      selector: "[data-testid='upload-zone']",
      tips: "Quality matters more than design—focus on clear content and real data.",
      location: "Upload instructions",
      order: 3,
    },
    {
      id: "upload-drag-drop",
      page: "onboarding-upload",
      title: "Drag & Drop or Click",
      description: "Simply drag your pitch deck file onto the upload zone, or click to browse your files. Once uploaded, our AI will begin processing immediately.",
      selector: "[data-testid='upload-zone']",
      tips: "Make sure you have the latest version of your deck before uploading.",
      location: "Upload interaction",
      order: 4,
    },
    {
      id: "upload-submit",
      page: "onboarding-upload",
      title: "Start Analysis",
      description: "After selecting your file, click 'Upload and Analyze' to submit your pitch deck. You'll be taken to a processing screen where you can watch the analysis in real-time.",
      selector: "[data-testid='button-upload-analyze']",
      tips: "Processing typically takes 30-90 seconds. Our AI reads your deck, extracts key metrics, and calculates your ProofScore.",
      location: "Submit button",
      order: 5,
    },
  ],
  "onboarding-processing": [
    {
      id: "processing-intro",
      page: "onboarding-processing",
      title: "AI Analysis in Progress",
      description: "Our AI is analyzing your pitch deck right now. It's extracting data, evaluating your business model, and calculating your initial ProofScore.",
      selector: "[data-testid='processing-status']",
      tips: "This usually takes 30-90 seconds. Don't refresh the page—the analysis will complete automatically.",
      location: "Status indicator",
      order: 1,
    },
    {
      id: "processing-steps",
      page: "onboarding-processing",
      title: "What's Happening?",
      description: "The AI is: (1) Extracting text and data from your deck, (2) Identifying key business metrics, (3) Evaluating completeness across 5 dimensions, (4) Assigning validation experiments, and (5) Calculating your ProofScore.",
      selector: "[data-testid='processing-status']",
      tips: "We use advanced natural language processing to understand your unique business model.",
      location: "Processing details",
      order: 2,
    },
    {
      id: "processing-wait",
      page: "onboarding-processing",
      title: "Almost There",
      description: "Once processing completes, you'll automatically be redirected to your analysis results where you can see your ProofScore, dimension breakdown, and next steps.",
      selector: "[data-testid='processing-status']",
      tips: "In rare cases, processing can take up to 2 minutes for very detailed decks.",
      location: "Waiting state",
      order: 3,
    },
  ],
  "onboarding-analysis": [
    {
      id: "analysis-intro",
      page: "onboarding-analysis",
      title: "Your ProofScore Results!",
      description: "Congratulations! Your pitch deck has been analyzed. You now have a ProofScore that reflects your startup's current validation level and investment readiness.",
      selector: "[data-testid='analysis-proofscore']",
      tips: "ProofScores range from 0-100. Don't worry if yours is lower than expected—that's why you're here to validate and improve!",
      location: "Score display",
      order: 1,
    },
    {
      id: "analysis-prooftags",
      page: "onboarding-analysis",
      title: "ProofTags Unlocked",
      description: "ProofTags are achievements showing specific validations you've completed. Your initial tags come from your pitch deck analysis. Unlock more by completing experiments!",
      selector: "[data-testid='prooftags-display']",
      tips: "Each ProofTag represents credible evidence investors care about.",
      location: "ProofTags section",
      order: 2,
    },
    {
      id: "analysis-dimensions",
      page: "onboarding-analysis",
      title: "Dimension Breakdown",
      description: "Your score is calculated across 5 dimensions: Desirability, Feasibility, Viability, Traction, and Readiness. See which areas are strong and which need validation work.",
      selector: "[data-testid='dimension-breakdown']",
      tips: "Focus on strengthening your weakest dimensions first—balanced validation impresses investors.",
      location: "Dimensions section",
      order: 3,
    },
    {
      id: "analysis-leaderboard",
      page: "onboarding-analysis",
      title: "Leaderboard Rankings",
      description: "See how you rank among other founders on the platform. The leaderboard shows ProofScores and ProofTags unlocked, creating friendly competition and community motivation.",
      selector: "[data-testid='leaderboard-section']",
      tips: "Rankings update in real-time as you complete experiments and upload proof documents. Climb the leaderboard by validating systematically!",
      location: "Leaderboard panel",
      order: 4,
    },
    {
      id: "analysis-key-insights",
      page: "onboarding-analysis",
      title: "Key Insights from AI Analysis",
      description: "Our AI has identified your venture's key strengths and areas for improvement. These insights are personalized based on your pitch deck content and show where to focus your validation efforts.",
      selector: "[data-testid='key-insights-section']",
      tips: "Green insights = strengths to leverage. Yellow insights = areas needing attention. Purple insights = recommended next steps.",
      location: "Key Insights section",
      order: 5,
    },
    {
      id: "analysis-pathway-button",
      page: "onboarding-analysis",
      title: "See My Pathway",
      description: "Click 'See My Pathway' to access your personalized development route. If your ProofScore is 70+, you'll go to Deal Room. Below 70, you'll access ProofScaling course to strengthen your fundamentals.",
      selector: "[data-testid='button-see-my-pathway']",
      tips: "Your pathway is customized to your current ProofScore. Both paths lead to investment readiness—just at different paces.",
      location: "Primary CTA button",
      order: 6,
    },
  ],
  "next-steps": [
    {
      id: "next-steps-intro",
      page: "next-steps",
      title: "Your Personalized Pathway",
      description: "Congratulations on completing your analysis! Based on your ProofScore, we've recommended the perfect package to accelerate your startup journey. This is a curated path designed specifically for your current stage.",
      selector: "[data-testid='button-get-started-payment']",
      tips: "Your pathway is personalized based on your ProofScore. Foundation Builder (< 70) strengthens fundamentals. Investment Ready (70+) accelerates fundraising.",
      location: "Full page view",
      order: 1,
    },
    {
      id: "next-steps-payment",
      page: "next-steps",
      title: "Get Started with Your Package",
      description: "Click 'Get Started' to unlock your personalized development package. You'll gain instant access to courses, templates, tools, and community support tailored to your venture's needs.",
      selector: "[data-testid='button-get-started-payment']",
      tips: "Secure payment processing with instant access. Includes 30-day money-back guarantee if you're not satisfied.",
      location: "Primary CTA button",
      order: 2,
    },
    {
      id: "next-steps-email",
      page: "next-steps",
      title: "Access via Email",
      description: "After payment, you'll receive an instant email with access links to all your premium content, courses, templates, and community channels. Check your inbox immediately after purchase.",
      selector: "[data-testid='email-confirmation-message']",
      tips: "Save the email—it contains your login credentials and all access links. Check spam folder if you don't see it within 2 minutes.",
      location: "FAQ section",
      order: 3,
    },
  ],
};

// Helper function to get journey step by ID
export function getJourneyStepById(id: number): JourneyStep | undefined {
  return COACH_JOURNEY_STEPS.find(step => step.id === id);
}

// Helper function to get next uncompleted step
export function getNextStep(completedSteps: number[]): JourneyStep | undefined {
  return COACH_JOURNEY_STEPS.find(step => !completedSteps.includes(step.id));
}

// Helper function to get tutorials for a specific page
export function getTutorialsForPage(page: string): TutorialMechanic[] {
  return TUTORIAL_MECHANICS[page] || [];
}
