import { Rocket, FileText, BarChart3, Award, Upload, CheckCircle, Users, CreditCard, MapPin, TrendingUp, Target, FolderOpen } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface JourneyStep {
  id: number;
  title: string;
  description: string;
  page: string; // Which page this step relates to
  duration: string;
  icon: LucideIcon;
  color: string;
  action: string; // CTA button text
  route?: string; // Optional route to navigate to
  selector?: string; // Optional data-testid for highlighting
  coachGuidance: {
    intro: string;
    instruction: string;
    tip?: string;
    nextStep?: string;
  };
  completionCriteria?: {
    checkField?: string; // Field to check in user/venture data
    minValue?: number; // For scores
    required?: boolean;
  };
  scoreThreshold?: {
    // Show different messages based on score
    low?: { max: number; message: string };
    medium?: { min: number; max: number; message: string };
    high?: { min: number; message: string };
  };
}

export const COACH_JOURNEY_STEPS: JourneyStep[] = [
  {
    id: 0,
    title: "Welcome to Second Chance",
    description: "Start your validation journey",
    page: "landing",
    duration: "2 min",
    icon: Rocket,
    color: "bg-blue-500",
    action: "Start Validation",
    route: "/onboarding-flow",
    coachGuidance: {
      intro: "Welcome! Let's transform your startup idea into an investor-ready venture.",
      instruction: "Click 'Start Validation' to begin your onboarding journey.",
      tip: "This process takes about 15 minutes and will give you your first ProofScore.",
      nextStep: "You'll provide founder details, venture information, and upload your pitch deck.",
    },
  },
  {
    id: 1,
    title: "Complete Onboarding",
    description: "Share your founder and venture details",
    page: "onboarding",
    duration: "10 min",
    icon: FileText,
    color: "bg-purple-500",
    action: "Continue Onboarding",
    route: "/onboarding-flow",
    coachGuidance: {
      intro: "Let's get your startup profile set up.",
      instruction: "Complete all onboarding steps: Founder Info → Venture Details → Team → Pitch Deck Upload.",
      tip: "Provide detailed information to get a more accurate ProofScore.",
      nextStep: "After completion, you'll receive your AI-powered ProofScore analysis.",
    },
    completionCriteria: {
      checkField: "onboardingComplete",
      required: true,
    },
  },
  {
    id: 2,
    title: "Review Your ProofScore",
    description: "Understand your validation score and insights",
    page: "dashboard",
    duration: "5 min",
    icon: BarChart3,
    color: "bg-green-500",
    action: "View Dashboard",
    route: "/dashboard",
    selector: "[data-testid='proofscore-display']",
    coachGuidance: {
      intro: "Your ProofScore reveals your startup's investment readiness.",
      instruction: "Review your score, dimension breakdown, and unlocked ProofTags.",
      tip: "ProofScores range from 0-100. Scores of 70+ unlock Deal Room access.",
      nextStep: "Explore the Validation Map to strengthen weak areas.",
    },
    scoreThreshold: {
      low: { max: 40, message: "Focus on building foundational proof through experiments." },
      medium: { min: 40, max: 70, message: "You're making progress! Complete validation experiments to boost your score." },
      high: { min: 70, message: "Excellent! You're ready for Deal Room access." },
    },
  },
  {
    id: 3,
    title: "Explore Validation Map",
    description: "Discover your personalized experiments",
    page: "validation-map",
    duration: "10 min",
    icon: MapPin,
    color: "bg-yellow-500",
    action: "Open Validation Map",
    route: "/validation-map",
    selector: "[data-testid='validation-map-grid']",
    coachGuidance: {
      intro: "Your Validation Map contains AI-curated experiments tailored to your startup.",
      instruction: "Review assigned experiments across Desirability, Feasibility, Viability, and Scaling spheres.",
      tip: "Each experiment tests a critical assumption about your business model.",
      nextStep: "Start running experiments and documenting results.",
    },
  },
  {
    id: 4,
    title: "Complete Your First Experiment",
    description: "Run and document a validation experiment",
    page: "validation-map",
    duration: "1-2 weeks",
    icon: Target,
    color: "bg-orange-500",
    action: "Start Experiment",
    route: "/validation-map",
    coachGuidance: {
      intro: "Time to validate your assumptions with real-world data!",
      instruction: "Pick an experiment, define your hypothesis, run it, and record your results.",
      tip: "Completed experiments unlock ProofTags and boost your credibility with investors.",
      nextStep: "Continue completing experiments to strengthen your validation.",
    },
    completionCriteria: {
      checkField: "hasCompletedExperiment",
      required: false,
    },
  },
  {
    id: 5,
    title: "Build Your ProofVault",
    description: "Upload validation documents and proof artifacts",
    page: "dashboard",
    duration: "15 min",
    icon: FolderOpen,
    color: "bg-indigo-500",
    action: "Upload to ProofVault",
    route: "/dashboard",
    selector: "[data-testid='proof-vault-section']",
    coachGuidance: {
      intro: "ProofVault is your organized repository of validation evidence.",
      instruction: "Upload documents like customer testimonials, metrics dashboards, demo videos, and financial models.",
      tip: "Each upload increases your VaultScore, showing investors you have systematic proof.",
      nextStep: "Aim for a VaultScore of 50+ by uploading diverse proof artifacts.",
    },
    completionCriteria: {
      checkField: "vaultScore",
      minValue: 30,
    },
  },
  {
    id: 6,
    title: "Download Your Certificate",
    description: "Get your ProofScore certificate",
    page: "dashboard",
    duration: "1 min",
    icon: Award,
    color: "bg-pink-500",
    action: "Download Certificate",
    route: "/dashboard",
    selector: "[data-testid='button-download-certificate']",
    coachGuidance: {
      intro: "Your ProofScore certificate validates your systematic approach.",
      instruction: "Download and share your certificate with accelerators, investors, or on LinkedIn.",
      tip: "This certificate demonstrates you've gone beyond a pitch deck to validate your venture.",
      nextStep: "Keep improving your score to increase your credibility.",
    },
  },
  {
    id: 7,
    title: "Unlock Deal Room Access",
    description: "Connect with verified investors",
    page: "dashboard",
    duration: "5 min",
    icon: Users,
    color: "bg-emerald-500",
    action: "Access Deal Room",
    route: "/dashboard",
    selector: "[data-testid='deal-room-section']",
    coachGuidance: {
      intro: "Deal Room connects high-scoring founders with active investors.",
      instruction: "If your ProofScore is 70+, you can unlock premium investor access.",
      tip: "Deal Room members get investor introductions, pitch practice, and fundraising support.",
      nextStep: "Complete payment to activate your Deal Room membership.",
    },
    completionCriteria: {
      checkField: "proofScore",
      minValue: 70,
    },
    scoreThreshold: {
      low: { max: 70, message: "Increase your ProofScore to 70+ to unlock Deal Room access." },
      high: { min: 70, message: "Congratulations! You qualify for Deal Room access." },
    },
  },
  {
    id: 8,
    title: "Activate Premium Features",
    description: "Unlock full platform access",
    page: "dashboard",
    duration: "3 min",
    icon: CreditCard,
    color: "bg-violet-500",
    action: "Upgrade Now",
    route: "/dashboard",
    coachGuidance: {
      intro: "Premium access unlocks investor matching, pitch coaching, and priority support.",
      instruction: "Complete payment to activate your Deal Room membership.",
      tip: "Investment: AED 499 or $149. Founders who use Deal Room are 3x more likely to secure meetings.",
      nextStep: "After payment, you'll get immediate access to our investor network.",
    },
    completionCriteria: {
      checkField: "hasDealRoomAccess",
      required: false,
    },
  },
  {
    id: 9,
    title: "Keep Building Proof",
    description: "Continuous validation journey",
    page: "dashboard",
    duration: "Ongoing",
    icon: TrendingUp,
    color: "bg-teal-500",
    action: "View Progress",
    route: "/dashboard",
    coachGuidance: {
      intro: "Validation is an ongoing process, not a one-time event.",
      instruction: "Keep running experiments, uploading proof, and improving your ProofScore.",
      tip: "Regular updates show investors you're making progress and learning from data.",
      nextStep: "Use the Validation Map and ProofVault to systematically strengthen your case.",
    },
  },
];

// Page-specific tutorial mechanics
export interface TutorialMechanic {
  id: string;
  page: string;
  title: string;
  description: string;
  selector: string; // data-testid to highlight
  tips?: string;
  location: string; // Where on screen to look
  order: number; // Sequence within page tutorial
}

export const TUTORIAL_MECHANICS: Record<string, TutorialMechanic[]> = {
  dashboard: [
    {
      id: "dashboard-header",
      page: "dashboard",
      title: "Dashboard Overview",
      description: "Your central hub for tracking validation progress, ProofScore, and accessing key features.",
      selector: "[data-testid='dashboard-header']",
      location: "Top of page",
      order: 1,
    },
    {
      id: "validation-overview",
      page: "dashboard",
      title: "Validation Overview",
      description: "Your current ProofScore (0-100) reflects your startup's investment readiness based on uploaded proof and completed experiments.",
      selector: "[data-testid='proofscore-display']",
      tips: "ProofScores of 70+ unlock Deal Room access.",
      location: "Upper section",
      order: 2,
    },
    {
      id: "deal-room",
      page: "dashboard",
      title: "Deal Room Access",
      description: "Unlock investor matching and fundraising support with a ProofScore of 70+. Book your first meeting here.",
      selector: "[data-testid='deal-room-section']",
      tips: "Deal Room members are 3x more likely to secure investor meetings.",
      location: "Upper right section",
      order: 3,
    },
    {
      id: "proof-vault",
      page: "dashboard",
      title: "ProofVault Management",
      description: "Upload and organize validation documents. Each upload increases your VaultScore and strengthens your investor case.",
      selector: "[data-testid='proof-vault-section']",
      tips: "Upload diverse artifacts: testimonials, metrics, videos, financial models.",
      location: "Main section",
      order: 4,
    },
    {
      id: "document-downloads",
      page: "dashboard",
      title: "Downloads Available",
      description: "Download your validation certificate and analysis report after unlocking Deal Room access.",
      selector: "[data-testid='document-downloads-section']",
      tips: "These documents are perfect for investor decks and pitch materials.",
      location: "Lower left section",
      order: 5,
    },
    {
      id: "community-access",
      page: "dashboard",
      title: "Community Access",
      description: "Connect with other founders and join exclusive events like Founders Live Egypt and UAE.",
      selector: "[data-testid='community-access-section']",
      tips: "Book 1-on-1 sessions via Calendly if you have Deal Room access.",
      location: "Lower right section",
      order: 6,
    },
    {
      id: "leaderboard",
      page: "dashboard",
      title: "Leaderboard",
      description: "See how you rank against other founders based on ProofScore and ProofTags unlocked.",
      selector: "[data-testid='leaderboard-section']",
      location: "Bottom left section",
      order: 7,
    },
    {
      id: "activity-feed",
      page: "dashboard",
      title: "Recent Activity",
      description: "Track your latest platform interactions, uploads, and achievements in real-time.",
      selector: "[data-testid='activity-feed-section']",
      location: "Bottom right section",
      order: 8,
    },
  ],
  "validation-map": [
    {
      id: "what-are-experiments",
      page: "validation-map",
      title: "What are Validation Experiments?",
      description: "Experiments are systematic tests to validate your startup's assumptions. Each experiment helps you gather evidence about whether your business model works, reducing risk and increasing investor confidence.",
      selector: "[data-testid='validation-map-intro']",
      tips: "Completing experiments unlocks ProofTags and boosts your ProofScore, making you more investment-ready.",
      location: "Top section",
      order: 1,
    },
    {
      id: "validation-spheres",
      page: "validation-map",
      title: "Four Validation Spheres",
      description: "Your experiments span four critical areas: Desirability (do customers want it?), Feasibility (can we build it?), Viability (will it make money?), and Scaling (can we grow it?).",
      selector: "[data-testid='validation-map-intro']",
      tips: "Balanced validation across all four spheres creates a compelling investor case.",
      location: "Introduction card",
      order: 2,
    },
    {
      id: "add-experiment",
      page: "validation-map",
      title: "Adding Experiments",
      description: "Click 'Add Experiment' to choose from 44 AI-curated experiments designed for your startup stage, or create custom experiments that match your unique validation needs.",
      selector: "[data-testid='experiment-header-card']",
      tips: "Start with 3-5 high-impact experiments. Quality matters more than quantity.",
      location: "Top right buttons",
      order: 3,
    },
    {
      id: "experiment-filters",
      page: "validation-map",
      title: "Search & Filter Tools",
      description: "Use search to find specific experiments, filter by validation sphere (Desirability, Feasibility, Viability, Scaling), or filter by status (pending, in-progress, completed) to stay organized.",
      selector: "[data-testid='experiment-filters-card']",
      tips: "Focus on completing experiments in areas where you have the least evidence first.",
      location: "Filter section",
      order: 4,
    },
    {
      id: "table-structure",
      page: "validation-map",
      title: "Understanding Your Experiment Table",
      description: "Each column represents a step in the scientific method: your hypothesis, what you'll measure, actual results, analysis (why), insights learned, and your decision (pivot, persevere, or iterate). Each row has action buttons (Edit, Delete, Complete) and supports inline editing—just click any editable field and changes auto-save after 500ms.",
      selector: "[data-testid='experiment-table-card']",
      tips: "Mark experiments 'Complete' to unlock ProofTags. This structured approach helps you think like a scientist about your business.",
      location: "Table area",
      order: 5,
    },
    {
      id: "export-csv",
      page: "validation-map",
      title: "Export to CSV",
      description: "After completing at least 3 experiments, use the 'Export CSV' button to download your validation map. This CSV file can be uploaded to your ProofVault to boost your VaultScore and strengthen your investor materials.",
      selector: "[data-testid='experiment-header-card']",
      tips: "The CSV export captures all your experiment data in a format investors can easily review. It's a powerful artifact showing systematic validation.",
      location: "Top right section",
      order: 6,
    },
  ],
  "experiment-details": [
    {
      id: "experiment-overview",
      page: "experiment-details",
      title: "Experiment Overview",
      description: "View your experiment's title, current status (pending, in-progress, completed), validation sphere (Desirability, Viability, Feasibility, Scaling), and associated ProofTag (if completed). The definition explains what this experiment tests.",
      selector: "[data-testid='experiment-modal-header']",
      tips: "Completed experiments unlock ProofTags that boost your ProofScore and show investors systematic validation.",
      location: "Top section",
      order: 1,
    },
    {
      id: "core-assumption",
      page: "experiment-details",
      title: "Core Assumption",
      description: "This is the fundamental belief your experiment tests. It's pre-populated from the AI-curated experiment library and helps you focus on what you're validating.",
      selector: "[data-testid='experiment-core-assumption']",
      tips: "Every successful startup is built on validated assumptions, not guesses.",
      location: "First field",
      order: 2,
    },
    {
      id: "hypothesis-field",
      page: "experiment-details",
      title: "Your Hypothesis",
      description: "Write your specific, testable prediction. Click Edit to activate the rich text editor and document what you expect to happen. A good hypothesis is clear, measurable, and time-bound.",
      selector: "[data-testid='experiment-hypothesis']",
      tips: "Example: 'If we add social proof testimonials, we'll see 15% increase in sign-ups within 2 weeks.'",
      location: "Second field",
      order: 3,
    },
    {
      id: "target-metrics",
      page: "experiment-details",
      title: "Target Behaviour & Metric",
      description: "These fields define what customer action you're testing (behaviour) and how you'll measure success (metric). They guide you to think scientifically about validation.",
      selector: "[data-testid='experiment-target-behaviour']",
      tips: "Combine both: What should users do? How will you measure it?",
      location: "Middle fields",
      order: 4,
    },
    {
      id: "actual-results",
      page: "experiment-details",
      title: "Actual Results",
      description: "Record what actually happened. Use the rich text editor to add data, screenshots, metrics, quotes—any evidence from your experiment. This is your proof.",
      selector: "[data-testid='experiment-results']",
      tips: "Be honest. Negative results teach as much as positive ones. Investors value learning velocity.",
      location: "Results section",
      order: 5,
    },
    {
      id: "analysis-insights",
      page: "experiment-details",
      title: "Analysis & Insights",
      description: "'Why?' analyzes what caused the results. 'New Insights' captures unexpected learnings. Both help you build institutional knowledge about your market and customers.",
      selector: "[data-testid='experiment-why']",
      tips: "This is where pivots are born. Document surprises—they often reveal better opportunities.",
      location: "Analysis fields",
      order: 6,
    },
    {
      id: "decision-making",
      page: "experiment-details",
      title: "Decision",
      description: "Choose your path forward: Go (validated, scale it), Start (begin this initiative), Pivot (change direction), or Learn/Measure (need more data). This turns validation into action.",
      selector: "[data-testid='experiment-decision']",
      tips: "Making decisions based on data (not opinions) is what separates funded startups from failed ones.",
      location: "Bottom field",
      order: 7,
    },
    {
      id: "edit-mode",
      page: "experiment-details",
      title: "Edit & Save",
      description: "Click the Edit button (top right) to enable editing mode. Update any editable fields using the rich text editor for formatting. When done, click Save Changes to update your experiment.",
      selector: "[data-testid='button-edit-experiment']",
      tips: "Changes auto-save in the table view, but modal editing gives you full rich text formatting capabilities.",
      location: "Top right buttons",
      order: 8,
    },
  ],
  "onboarding-founder": [
    {
      id: "founder-intro",
      page: "onboarding-founder",
      title: "Welcome to Onboarding!",
      description: "Let's get started with your founder profile. This information helps us understand your background and expertise, which factors into your ProofScore calculation.",
      selector: "[data-testid='onboarding-founder-form']",
      tips: "The onboarding process takes about 10-15 minutes total. You can save progress and return later if needed.",
      location: "Full form",
      order: 1,
    },
    {
      id: "founder-name",
      page: "onboarding-founder",
      title: "Your Full Name",
      description: "Enter your full name as it appears professionally. This will be used on your ProofScore certificate and investor communications.",
      selector: "[data-testid='input-full-name']",
      tips: "Use your real name—authenticity builds trust with investors.",
      location: "First field",
      order: 2,
    },
    {
      id: "founder-email",
      page: "onboarding-founder",
      title: "Email Address",
      description: "Provide your primary email address. This will be used for login, notifications about your validation progress, and investor communications.",
      selector: "[data-testid='input-email']",
      tips: "Use a professional email you check regularly—important updates about your ProofScore and Deal Room will be sent here.",
      location: "Second field",
      order: 3,
    },
    {
      id: "founder-position",
      page: "onboarding-founder",
      title: "Position/Role",
      description: "Specify your role in the venture (e.g., CEO, CTO, Founder, Co-Founder). This helps us understand your leadership position and responsibilities.",
      selector: "[data-testid='input-position-role']",
      tips: "If you have multiple roles, list the primary one. Technical roles (CTO, Lead Engineer) can positively influence feasibility scores.",
      location: "Third field",
      order: 4,
    },
    {
      id: "founder-demographics",
      page: "onboarding-founder",
      title: "Age & Gender (Optional)",
      description: "Providing demographic information is optional but helps us understand founder diversity patterns. This data is kept private and used only for anonymized analytics.",
      selector: "[data-testid='input-age']",
      tips: "These fields are optional and won't affect your ProofScore. We use this data to improve our platform and support diverse founder communities.",
      location: "Age and Gender fields",
      order: 5,
    },
    {
      id: "founder-residence",
      page: "onboarding-founder",
      title: "Residence Location",
      description: "Enter your current city and country (e.g., 'Dubai, UAE' or 'San Francisco, USA'). This helps us connect you with local investor networks and relevant resources.",
      selector: "[data-testid='input-residence']",
      tips: "Your location influences which payment options and investor networks we can offer you.",
      location: "Residence field",
      order: 6,
    },
    {
      id: "founder-linkedin",
      page: "onboarding-founder",
      title: "LinkedIn Profile",
      description: "Add your LinkedIn profile URL. A complete LinkedIn profile with relevant experience, education, and network demonstrates credibility to investors.",
      selector: "[data-testid='input-linkedin']",
      tips: "Investors often research founders on LinkedIn before meetings. Make sure your profile is up-to-date and professional.",
      location: "LinkedIn field",
      order: 7,
    },
    {
      id: "founder-technical",
      page: "onboarding-founder",
      title: "Technical Background",
      description: "Toggle this on if you have technical skills like coding, engineering, data science, or product development. Tech-capable founders often score higher in feasibility validation.",
      selector: "[data-testid='switch-is-technical']",
      tips: "Technical founders can build MVPs faster and validate solutions more efficiently. But non-technical founders with great teams also succeed!",
      location: "Technical toggle",
      order: 8,
    },
    {
      id: "founder-submit",
      page: "onboarding-founder",
      title: "Continue to Venture Info",
      description: "Once you've completed your founder profile, click 'Next: Venture Info' to move on to describing your startup, problem, solution, and market opportunity.",
      selector: "[data-testid='button-continue-venture']",
      tips: "All this information can be edited later from your dashboard settings.",
      location: "Bottom button",
      order: 9,
    },
  ],
  "onboarding-venture": [
    {
      id: "venture-intro",
      page: "onboarding-venture",
      title: "Tell Us About Your Startup",
      description: "Now let's capture details about your venture. This information is critical for your ProofScore calculation and helps us assign relevant validation experiments tailored to your business.",
      selector: "[data-testid='onboarding-venture-form']",
      tips: "Be specific and honest—our AI analyzes your pitch deck against these details to generate accurate insights.",
      location: "Full form",
      order: 1,
    },
    {
      id: "venture-name",
      page: "onboarding-venture",
      title: "Startup Name",
      description: "Enter your company's official name. This will be used in your ProofScore certificate, investor communications, and all platform documentation.",
      selector: "[data-testid='input-company-name']",
      tips: "Use your registered business name or the name you plan to register. This appears on all official documents.",
      location: "First field",
      order: 2,
    },
    {
      id: "venture-industry-geography",
      page: "onboarding-venture",
      title: "Industry & Geography",
      description: "Select your primary industry sector and target geography. These help us connect you with relevant investors, benchmarks, and market opportunities specific to your domain.",
      selector: "[data-testid='select-industry']",
      tips: "Choose the industry that best describes your core business. Geography should reflect where you'll operate or seek customers.",
      location: "Industry and Geography fields",
      order: 3,
    },
    {
      id: "venture-business-model",
      page: "onboarding-venture",
      title: "Business Model",
      description: "Define how your startup makes money. Your business model (B2B SaaS, Marketplace, E-commerce, etc.) influences which validation experiments we assign and how investors evaluate you.",
      selector: "[data-testid='select-business-model']",
      tips: "Choose the model that best describes your revenue generation approach. This affects your ProofScore calculation.",
      location: "Business Model field",
      order: 4,
    },
    {
      id: "venture-revenue-product",
      page: "onboarding-venture",
      title: "Revenue & Product Stage",
      description: "Indicate your current revenue stage (Pre-Revenue, Early Revenue, Scaling) and product status (Mockup, Prototype, Launched). These stages determine which validation pathways are most relevant.",
      selector: "[data-testid='select-revenue-stage']",
      tips: "Be honest about your stage—early-stage startups get different experiments than launched products. Both paths can succeed!",
      location: "Revenue and Product fields",
      order: 5,
    },
    {
      id: "venture-website",
      page: "onboarding-venture",
      title: "Website (Optional)",
      description: "Add your company website URL if you have one. A live website demonstrates traction and professionalism to investors, though it's not required at early stages.",
      selector: "[data-testid='input-website']",
      tips: "No website yet? No problem! Many successful startups begin without one. You can add it later as you grow.",
      location: "Website field",
      order: 6,
    },
    {
      id: "venture-description",
      page: "onboarding-venture",
      title: "Startup Description",
      description: "Write a clear, compelling description of what your startup does, the problem you solve, and your unique value proposition. This is analyzed by our AI for clarity and market fit.",
      selector: "[data-testid='textarea-problem-statement']",
      tips: "Great descriptions answer: What problem exists? Who has it? How do you solve it differently? Keep it concise and specific.",
      location: "Description field",
      order: 7,
    },
    {
      id: "venture-social",
      page: "onboarding-venture",
      title: "Social Media Links (Optional)",
      description: "Add links to your company's LinkedIn, Twitter/X, and Instagram profiles. Social media presence shows market engagement and can boost investor confidence.",
      selector: "[data-testid='input-linkedin-url']",
      tips: "Active social channels demonstrate community building and marketing efforts. Optional but recommended for visibility.",
      location: "Social media fields",
      order: 8,
    },
    {
      id: "venture-submit",
      page: "onboarding-venture",
      title: "Continue to Team",
      description: "Once you've completed all venture details, click 'Next: Team Members' to add your team (optional) or proceed directly to uploading your pitch deck.",
      selector: "[data-testid='button-continue-team']",
      tips: "Strong teams increase ProofScore significantly—investors bet on people as much as ideas!",
      location: "Bottom button",
      order: 9,
    },
  ],
  "onboarding-team": [
    {
      id: "team-intro",
      page: "onboarding-team",
      title: "Build Your Team Profile",
      description: "Add up to 4 team members. Investors love seeing complementary skills and diverse expertise. If you're solo for now, you can skip this step.",
      selector: "[data-testid='onboarding-team-form']",
      tips: "Teams with balanced skills (tech + business, for example) tend to score higher.",
      location: "Full form",
      order: 1,
    },
    {
      id: "team-members",
      page: "onboarding-team",
      title: "Adding Team Members",
      description: "For each team member, provide their name, role, and LinkedIn profile. Show investors you have the right people to execute your vision.",
      selector: "[data-testid='team-member-input']",
      tips: "Include advisors or key early hires if they're actively contributing.",
      location: "Team member fields",
      order: 2,
    },
    {
      id: "team-skip",
      page: "onboarding-team",
      title: "Skip if Solo",
      description: "If you're a solo founder right now, click 'Skip' to move forward. You can always add team members later as you grow.",
      selector: "[data-testid='button-skip-team']",
      tips: "Solo founders can succeed—focus on showing traction and learning velocity.",
      location: "Skip button",
      order: 3,
    },
    {
      id: "team-submit",
      page: "onboarding-team",
      title: "Move to Upload",
      description: "When you're done adding team members (or skipping), click 'Continue to Upload' to share your pitch deck for AI analysis.",
      selector: "[data-testid='button-continue-upload']",
      tips: "The next step is critical—your pitch deck drives your initial ProofScore.",
      location: "Bottom button",
      order: 4,
    },
  ],
  "onboarding-upload": [
    {
      id: "upload-intro",
      page: "onboarding-upload",
      title: "Upload Your Pitch Deck",
      description: "This is the most important step! Our AI will analyze your pitch deck to generate your ProofScore and assign personalized validation experiments.",
      selector: "[data-testid='upload-zone']",
      tips: "Accepted formats: PDF, PPTX, PPT. Max size: 10MB. Make sure your deck has slides about problem, solution, market, traction, and team.",
      location: "Upload area",
      order: 1,
    },
    {
      id: "upload-requirements",
      page: "onboarding-upload",
      title: "What Makes a Good Deck?",
      description: "Include slides covering: problem statement, solution/product, market opportunity, business model, traction metrics, competitive landscape, and team. The more complete your deck, the better your ProofScore.",
      selector: "[data-testid='upload-zone']",
      tips: "Quality matters more than design—focus on clear content and real data.",
      location: "Upload instructions",
      order: 2,
    },
    {
      id: "upload-drag-drop",
      page: "onboarding-upload",
      title: "Drag & Drop or Click",
      description: "Simply drag your pitch deck file onto the upload zone, or click to browse your files. Once uploaded, our AI will begin processing immediately.",
      selector: "[data-testid='upload-zone']",
      tips: "Make sure you have the latest version of your deck before uploading.",
      location: "Upload interaction",
      order: 3,
    },
    {
      id: "upload-submit",
      page: "onboarding-upload",
      title: "Start Analysis",
      description: "After selecting your file, click 'Upload and Analyze' to submit your pitch deck. You'll be taken to a processing screen where you can watch the analysis in real-time.",
      selector: "[data-testid='button-upload-analyze']",
      tips: "Processing typically takes 30-90 seconds. Our AI reads your deck, extracts key metrics, and calculates your ProofScore.",
      location: "Submit button",
      order: 4,
    },
  ],
  "onboarding-processing": [
    {
      id: "processing-intro",
      page: "onboarding-processing",
      title: "AI Analysis in Progress",
      description: "Our AI is analyzing your pitch deck right now. It's extracting data, evaluating your business model, and calculating your initial ProofScore.",
      selector: "[data-testid='processing-status']",
      tips: "This usually takes 30-90 seconds. Don't refresh the page—the analysis will complete automatically.",
      location: "Status indicator",
      order: 1,
    },
    {
      id: "processing-steps",
      page: "onboarding-processing",
      title: "What's Happening?",
      description: "The AI is: (1) Extracting text and data from your deck, (2) Identifying key business metrics, (3) Evaluating completeness across 9 dimensions, (4) Assigning validation experiments, and (5) Calculating your ProofScore.",
      selector: "[data-testid='processing-status']",
      tips: "We use advanced natural language processing to understand your unique business model.",
      location: "Processing details",
      order: 2,
    },
    {
      id: "processing-wait",
      page: "onboarding-processing",
      title: "Almost There",
      description: "Once processing completes, you'll automatically be redirected to your analysis results where you can see your ProofScore, dimension breakdown, and next steps.",
      selector: "[data-testid='processing-status']",
      tips: "In rare cases, processing can take up to 2 minutes for very detailed decks.",
      location: "Waiting state",
      order: 3,
    },
  ],
  "onboarding-analysis": [
    {
      id: "analysis-intro",
      page: "onboarding-analysis",
      title: "Your ProofScore Results!",
      description: "Congratulations! Your pitch deck has been analyzed. You now have a ProofScore that reflects your startup's current validation level and investment readiness.",
      selector: "[data-testid='analysis-proofscore']",
      tips: "ProofScores range from 0-100. Don't worry if yours is lower than expected—that's why you're here to validate and improve!",
      location: "Score display",
      order: 1,
    },
    {
      id: "analysis-dimensions",
      page: "onboarding-analysis",
      title: "Dimension Breakdown",
      description: "Your score is calculated across 9 dimensions: Problem, Solution, Market, Business Model, Traction, Competition, Team, Financials, and Ask. See which areas are strong and which need validation work.",
      selector: "[data-testid='dimension-breakdown']",
      tips: "Focus on strengthening your weakest dimensions first—balanced validation impresses investors.",
      location: "Dimensions section",
      order: 2,
    },
    {
      id: "analysis-prooftags",
      page: "onboarding-analysis",
      title: "ProofTags Unlocked",
      description: "ProofTags are achievements showing specific validations you've completed. Your initial tags come from your pitch deck analysis. Unlock more by completing experiments!",
      selector: "[data-testid='prooftags-display']",
      tips: "Each ProofTag represents credible evidence investors care about.",
      location: "ProofTags section",
      order: 3,
    },
    {
      id: "analysis-next-steps",
      page: "onboarding-analysis",
      title: "Next Steps",
      description: "From here, you can go to your dashboard to see the full picture, explore your Validation Map with assigned experiments, or (if your score is 70+) unlock Deal Room access to connect with investors.",
      selector: "[data-testid='analysis-cta-buttons']",
      tips: "Most founders start with the Validation Map to begin systematic testing of their assumptions.",
      location: "Action buttons",
      order: 4,
    },
    {
      id: "analysis-dashboard",
      page: "onboarding-analysis",
      title: "Go to Dashboard",
      description: "Click 'Go to Dashboard' to see your complete validation hub. Your ProofScore, VaultScore, experiments, and all platform features live there.",
      selector: "[data-testid='button-go-dashboard']",
      tips: "The dashboard is your command center—bookmark it!",
      location: "Primary CTA",
      order: 5,
    },
  ],
};

// Helper function to get journey step by ID
export function getJourneyStepById(id: number): JourneyStep | undefined {
  return COACH_JOURNEY_STEPS.find(step => step.id === id);
}

// Helper function to get next uncompleted step
export function getNextStep(completedSteps: number[]): JourneyStep | undefined {
  return COACH_JOURNEY_STEPS.find(step => !completedSteps.includes(step.id));
}

// Helper function to get tutorials for a specific page
export function getTutorialsForPage(page: string): TutorialMechanic[] {
  return TUTORIAL_MECHANICS[page] || [];
}
